// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmUMS2qxIXmj_KwRMpW6PaKeU3H-LKMTQ',
    appId: '1:1037372885889:web:db2d377ae44c1a700bb680',
    messagingSenderId: '1037372885889',
    projectId: 'notification-453d4',
    authDomain: 'notification-453d4.firebaseapp.com',
    storageBucket: 'notification-453d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDriAkCsCS4HYUUwyesTg3WpBf-IAWyidg',
    appId: '1:1037372885889:android:ba450dcece5a3bad0bb680',
    messagingSenderId: '1037372885889',
    projectId: 'notification-453d4',
    storageBucket: 'notification-453d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RDiIS6EklBb_zx0uzg0OISOmJ9SM0XU',
    appId: '1:1037372885889:ios:21d326e819211fdf0bb680',
    messagingSenderId: '1037372885889',
    projectId: 'notification-453d4',
    storageBucket: 'notification-453d4.appspot.com',
    iosBundleId: 'com.example.testCammob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6RDiIS6EklBb_zx0uzg0OISOmJ9SM0XU',
    appId: '1:1037372885889:ios:21d326e819211fdf0bb680',
    messagingSenderId: '1037372885889',
    projectId: 'notification-453d4',
    storageBucket: 'notification-453d4.appspot.com',
    iosBundleId: 'com.example.testCammob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmUMS2qxIXmj_KwRMpW6PaKeU3H-LKMTQ',
    appId: '1:1037372885889:web:fa776d3bc61a301c0bb680',
    messagingSenderId: '1037372885889',
    projectId: 'notification-453d4',
    authDomain: 'notification-453d4.firebaseapp.com',
    storageBucket: 'notification-453d4.appspot.com',
  );
}
